# Generated by Django 6.0 on 2025-12-30 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('processing', '진행'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='core_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='core_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='문서 제목')),
                ('content', models.TextField(verbose_name='문서 내용')),
                ('status', models.CharField(choices=[('draft', '임시저장 (AI 작성중)'), ('pending', '결재대기 (검토필요)'), ('approved', '최종승인'), ('rejected', '반려됨')], default='draft', max_length=20, verbose_name='문서 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafted_approvals', to='core.agent', verbose_name='AI 기안자')),
                ('drafter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafted_approvals', to=settings.AUTH_USER_MODEL, verbose_name='사람 기안자')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=1, verbose_name='결재 순서')),
                ('status', models.CharField(choices=[('pending', '대기'), ('current', '검토중'), ('approved', '승인'), ('rejected', '반려')], default='pending', max_length=20, verbose_name='결재 상태')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='검토 의견')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.approval', verbose_name='결재문서')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals_to_review', to=settings.AUTH_USER_MODEL, verbose_name='결재자')),
            ],
            options={
                'ordering': ['step'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '사장님'), ('assistant', 'AI 직원')], max_length=20)),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
