# Generated by Django 6.0 on 2025-12-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_status_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='department',
            field=models.CharField(default='국제금융실', max_length=50, verbose_name='소속 부서'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='model_name',
            field=models.CharField(default='gpt-5-nano', max_length=50, verbose_name='사용 모델'),
        ),
    ]
