# Generated by Django 6.0 on 2025-12-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agent_department_alter_agent_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='ticker',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='관리 종목코드(예: SPY)'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='model_name',
            field=models.CharField(default='gpt-4o', max_length=50, verbose_name='사용 모델'),
        ),
    ]
