# Generated by Django 6.0 on 2026-01-03 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agent_ticker_alter_agent_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='position',
            field=models.CharField(default='실장', max_length=50, verbose_name='직급'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=50, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.organization', verbose_name='소속 회사'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='ticker',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='관리 종목코드'),
        ),
    ]
