# Generated by Django 6.0 on 2026-01-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agent_position_alter_agent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='agents/', verbose_name='프로필 이미지'),
        ),
    ]
