# Generated by Django 5.2.9 on 2026-01-04 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_agent_id_alter_approval_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='사번'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='직급'),
        ),
        migrations.CreateModel(
            name='InvestmentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20, verbose_name='종목코드')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='매수금액')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='평균단가')),
                ('status', models.CharField(choices=[('draft', '기안중'), ('approved', '승인완료'), ('rejected', '반려')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agent', verbose_name='담당 AI 직원')),
            ],
        ),
        migrations.AddField(
            model_name='approval',
            name='investment_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_doc', to='core.investmentlog'),
        ),
    ]
