# Generated by Django 5.2.9 on 2026-01-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_employee_id_user_position_investmentlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='report_type',
            field=models.CharField(choices=[('buy', '매수보고'), ('sell', '매도보고'), ('perf', '성과보고'), ('market', '시장보고'), ('gen', '일반기안')], default='gen', max_length=10, verbose_name='보고 유형'),
        ),
        migrations.AddField(
            model_name='approval',
            name='temp_date',
            field=models.DateField(blank=True, null=True, verbose_name='거래/분석 일자'),
        ),
        migrations.AddField(
            model_name='approval',
            name='temp_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='성과 종료일'),
        ),
        migrations.AddField(
            model_name='approval',
            name='temp_extra_info',
            field=models.TextField(blank=True, null=True, verbose_name='추가 상세내용'),
        ),
        migrations.AddField(
            model_name='approval',
            name='temp_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='임시 수량'),
        ),
        migrations.AddField(
            model_name='approval',
            name='temp_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='성과 시작일'),
        ),
        migrations.AddField(
            model_name='approval',
            name='temp_stock_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='임시 종목코드'),
        ),
        migrations.AddField(
            model_name='approval',
            name='temp_total_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='임시 거래금액'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('draft', '임시저장'), ('pending', '결재대기'), ('approved', '최종승인'), ('rejected', '반려됨')], default='pending', max_length=20, verbose_name='문서 상태'),
        ),
        migrations.AlterField(
            model_name='investmentlog',
            name='status',
            field=models.CharField(choices=[('approved', '승인완료'), ('rejected', '반려')], default='approved', max_length=10),
        ),
        migrations.AlterField(
            model_name='investmentlog',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='거래금액'),
        ),
    ]
