# Generated by Django 5.2.9 on 2026-01-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_approval_report_type_approval_temp_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='temp_stock_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='임시 종목명'),
        ),
        migrations.AddField(
            model_name='investmentlog',
            name='stock_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='종목명'),
        ),
    ]
