# Generated by Django 5.2.9 on 2026-01-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_approval_temp_stock_name_investmentlog_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentlog',
            name='stock_name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='종목명'),
        ),
    ]
