# Generated by Django 5.2.9 on 2026-01-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_investmentlog_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='temp_stock_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='임시 종목명'),
        ),
        migrations.AlterField(
            model_name='investmentlog',
            name='stock_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='종목코드'),
        ),
        migrations.AlterField(
            model_name='investmentlog',
            name='stock_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='종목명'),
        ),
    ]
