# Generated by Django 5.2.9 on 2026-01-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_approval_temp_stock_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='종목명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='종목코드')),
                ('current_price', models.IntegerField(blank=True, null=True, verbose_name='현재가')),
                ('high_52w', models.IntegerField(blank=True, null=True, verbose_name='52주 고가')),
                ('low_52w', models.IntegerField(blank=True, null=True, verbose_name='52주 저가')),
                ('candle_data', models.JSONField(default=list, verbose_name='캔들 데이터(종가)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최근 업데이트')),
            ],
        ),
    ]
