# Generated by Django 5.2.9 on 2026-01-05 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='ticker',
        ),
        migrations.AddField(
            model_name='agent',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stock', verbose_name='관리 종목'),
        ),
    ]
