# Generated by Django 5.2.9 on 2026-01-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_agent_ticker_agent_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='현재가'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='high_52w',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='52주 고가'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low_52w',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='52주 저가'),
        ),
    ]
