# Generated by Django 5.2.9 on 2026-01-08 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_stock_current_price_alter_stock_high_52w_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentlog',
            name='order_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='주문번호'),
        ),
        migrations.AddField(
            model_name='investmentlog',
            name='source',
            field=models.CharField(choices=[('ai', '🤖 AI기안'), ('real', '📱 실거래')], default='ai', max_length=10, verbose_name='출처'),
        ),
        migrations.AddField(
            model_name='investmentlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='investmentlog',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.agent', verbose_name='담당 AI 직원'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(blank=True, max_length=100, unique=True, verbose_name='연동 API Key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
