# Generated by Django 5.2.9 on 2026-01-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='department_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='core.department', verbose_name='소속 부서 (연동)'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='department',
            field=models.CharField(default='국제금융실', max_length=50, verbose_name='소속 부서 (텍스트)'),
        ),
    ]
