# Generated by Django 5.2.9 on 2026-01-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_agent_department_obj_alter_agent_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='department',
        ),
    ]
