# Generated by Django 5.2.9 on 2026-01-11 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_agent_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='현금 잔고'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', '입금'), ('WITHDRAW', '출금'), ('BUY', '매수'), ('SELL', '매도'), ('DIVIDEND', '배당'), ('EXPENSE', '비용/지출')], max_length=20, verbose_name='거래 유형')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='변동 금액')),
                ('quantity', models.IntegerField(default=0, verbose_name='수량 변동')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='단가')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='잔액 스냅샷')),
                ('description', models.TextField(blank=True, verbose_name='적요')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='일시')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.organization')),
                ('related_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stock', verbose_name='관련 자산(종목)')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='기준 일자')),
                ('total_cash', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='현금 자산')),
                ('total_stock_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='주식 평가액')),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='총 자산')),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='총 부채')),
                ('total_equity', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='자본 총계')),
                ('realized_pl', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='누적 실현 손익')),
                ('unrealized_pl', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='평가 손익')),
                ('net_income', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='당기 순이익(추정)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='core.organization')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('organization', 'date')},
            },
        ),
    ]
