# Generated by Django 5.2.9 on 2026-01-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_organization_cash_balance_transaction_dailysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='profit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='실현손익 (Profit)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='거래 후 잔액'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='단가'),
        ),
    ]
