# Generated by Django 5.2.9 on 2026-01-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_transaction_profit_alter_transaction_balance_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='model_name',
            field=models.CharField(default='gpt-5-nano', max_length=50, verbose_name='사용 모델'),
        ),
    ]
