# Generated by Django 5.2.9 on 2026-01-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_agent_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='사번'),
        ),
    ]
