# Generated by Django 5.2.9 on 2026-01-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_agent_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysnapshot',
            name='capital_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='자본금'),
        ),
        migrations.AddField(
            model_name='dailysnapshot',
            name='retained_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='이익잉여금'),
        ),
        migrations.AddField(
            model_name='dailysnapshot',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='누적 수수료'),
        ),
        migrations.AddField(
            model_name='dailysnapshot',
            name='total_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='누적 세금'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='수수료'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='세금'),
        ),
    ]
