# Generated by Django 5.2.9 on 2026-01-11 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_dailysnapshot_capital_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True, verbose_name='기업 개요'),
        ),
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='시가총액'),
        ),
        migrations.AddField(
            model_name='stock',
            name='pbr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PBR'),
        ),
        migrations.AddField(
            model_name='stock',
            name='per',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PER'),
        ),
        migrations.CreateModel(
            name='InterestStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='core.stock', verbose_name='종목')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_stocks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '관심 종목',
                'verbose_name_plural': '관심 종목 목록',
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
