# Generated by Django 5.2.9 on 2026-01-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_stock_description_stock_market_cap_stock_pbr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='국가'),
        ),
    ]
