# Generated by Django 5.2.9 on 2026-01-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_stock_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='표시 순서'),
        ),
    ]
