# Generated by Django 5.2.9 on 2026-01-13 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_stock_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentlog',
            name='source',
            field=models.CharField(choices=[('ceo', '👑 CEO'), ('sms', '📱 SMS')], default='ceo', max_length=10, verbose_name='출처'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_institution', models.CharField(max_length=50, verbose_name='금융회사명')),
                ('account_number', models.CharField(max_length=50, verbose_name='계좌번호')),
                ('account_holder', models.CharField(max_length=50, verbose_name='예금주명')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='계좌별명')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 계좌 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.organization', verbose_name='소속 회사')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.account', verbose_name='거래 계좌'),
        ),
    ]
