# Generated by Django 5.2.9 on 2026-01-14 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_investmentlog_source_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='stock',
        ),
        migrations.AddField(
            model_name='stock',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stocks', to='core.agent', verbose_name='담당 AI'),
        ),
    ]
