# Generated by Django 5.2.9 on 2026-01-14 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_agent_stock_stock_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='SMS 원본 내용')),
                ('stock_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='종목명')),
                ('stock_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='종목코드')),
                ('trade_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='매매구분')),
                ('quantity', models.IntegerField(default=0, verbose_name='수량')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='단가')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총 금액')),
                ('is_parsed', models.BooleanField(default=False, verbose_name='파싱 성공 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='수신 일시')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
