# Generated by Django 5.2.9 on 2026-01-14 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_tradenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='temp_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.account', verbose_name='임시 매수 계좌'),
        ),
        migrations.AddField(
            model_name='investmentlog',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.account', verbose_name='매수 계좌'),
        ),
    ]
