# Generated by Django 5.2.9 on 2026-01-17 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_approval_temp_account_investmentlog_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='전략명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('logic', models.JSONField(verbose_name='로직 설정(JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stock', verbose_name='대상 종목(선택)')),
            ],
        ),
    ]
