# Generated by Django 5.2.9 on 2026-01-17 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.approval', verbose_name='원인 기안문'),
        ),
    ]
