# Generated by Django 5.2.9 on 2026-01-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_transaction_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='principles',
            field=models.TextField(blank=True, default='', verbose_name='나의 원칙'),
        ),
    ]
