# Generated by Django 5.2.9 on 2026-01-17 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_organization_logo_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='메뉴명')),
                ('url_name', models.CharField(max_length=100, verbose_name='URL 패턴명')),
                ('icon', models.CharField(default='📌', max_length=50, verbose_name='아이콘')),
                ('display_order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
