# Generated by Django 5.2.9 on 2026-01-18 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_userfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentlog',
            name='action',
            field=models.CharField(choices=[('buy', '매수'), ('sell', '매도')], default='buy', max_length=10, verbose_name='매매 종류'),
        ),
        migrations.AddField(
            model_name='investmentlog',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.stock', verbose_name='종목'),
        ),
        migrations.AddField(
            model_name='investmentlog',
            name='stock_market',
            field=models.CharField(default='KR', max_length=20, verbose_name='시장 (KR/US)'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_holder',
            field=models.CharField(default='', max_length=50, verbose_name='예금주명'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='', max_length=50, verbose_name='계좌번호'),
        ),
        migrations.AlterField(
            model_name='account',
            name='financial_institution',
            field=models.CharField(default='', max_length=50, verbose_name='금융회사명'),
        ),
        migrations.AlterField(
            model_name='account',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='계좌별명'),
        ),
        migrations.AlterField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.organization', verbose_name='소속 회사'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.organization', verbose_name='소속 회사'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='persona',
            field=models.TextField(default='', verbose_name='프롬프트(페르소나)'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(default='', max_length=100, verbose_name='담당 업무'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AlterField(
            model_name='dailysnapshot',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='dailysnapshot',
            name='total_assets',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='총 자산'),
        ),
        migrations.AlterField(
            model_name='dailysnapshot',
            name='total_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='현금 자산'),
        ),
        migrations.AlterField(
            model_name='dailysnapshot',
            name='total_equity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='자본 총계'),
        ),
        migrations.AlterField(
            model_name='dailysnapshot',
            name='total_stock_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='주식 평가액'),
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='소속 회사'),
        ),
        migrations.AlterField(
            model_name='investmentlog',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agent', verbose_name='담당 AI 에이전트'),
        ),
        migrations.AlterField(
            model_name='investmentlog',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='investmentlog',
            name='source',
            field=models.CharField(choices=[('direct', '직접'), ('agent', 'AI')], default='direct', max_length=20, verbose_name='거래 주체'),
        ),
        migrations.AlterField(
            model_name='investmentlog',
            name='status',
            field=models.CharField(choices=[('pending', '대기중'), ('approved', '승인됨'), ('rejected', '거절됨')], default='approved', max_length=10),
        ),
        migrations.AlterField(
            model_name='investmentlog',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='거래금액'),
        ),
        migrations.AlterField(
            model_name='investmentlog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='회사 설명'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='국가'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='기업 개요'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='지시자'),
        ),
        migrations.AlterField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AlterField(
            model_name='tradenotification',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='변동 금액'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='거래 후 잔액'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', '입금'), ('WITHDRAW', '출금'), ('BUY', '매수'), ('SELL', '매도'), ('DIVIDEND', '배당'), ('EXPENSE', '비용/지출')], default='DEPOSIT', max_length=20, verbose_name='거래 유형'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='별명'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('market', '시황'), ('strategy', '전략'), ('asset', '자산')], max_length=20, verbose_name='카테고리')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.organization', verbose_name='소속 회사')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='팔로워')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='팔로잉')),
            ],
            options={
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioDisclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosures', to='core.stock', verbose_name='종목')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_disclosures', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
