# Generated by Django 5.2.9 on 2026-01-18 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_investmentlog_action_investmentlog_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='target_stock',
        ),
        migrations.AddField(
            model_name='strategy',
            name='ticker',
            field=models.CharField(blank=True, help_text='대상 종목 코드 (Optional)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='logic',
            field=models.JSONField(default=dict, help_text='전략 로직 (매수/매도/DCA)'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
